export const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL;
export const SESSION = "GET_AI_ASSIST_SESSION";
export const REFRESH_TOKEN = "GET_AI_ASSIST_REFRESH_TOKEN";
export const USER_ID = "GET_AI_ASSIST_USER_ID";
export const LANGUAGE = "GET_AI_ASSIST_LANGUAGE";
